apiVersion: apps/v1
kind: Deployment
metadata:
  name: appCozinha
  labels:
    app: appCozinha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appCozinha
  template:
    metadata:
      labels:
        app: appCozinha
    spec:
      containers:
        - name: appCozinha
          image: mrpauloii/micro_cozinha_lanchonete:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_URL
            - name: DB_KIND
              value: "postgresql"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-jwt
                  key: JWT
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret-cozinha
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-cozinha
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-cozinha 
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"