apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cliente
  labels:
    app: app-cliente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-cliente
  template:
    metadata:
      labels:
        app: app-cliente
    spec:
      containers:
        - name: app-cliente
          image: mrpauloii/micro_cliente_lanchonete:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_KIND
              value: "postgresql"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-jwt
                  key: JWT
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret-cliente
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret-cliente
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret-cliente
                  key: POSTGRES_PASSWORD
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"