apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  URL: bW9uZ29kYitzcnY6Ly9tcnBhdWxvaWk6MzMzNjUyNjBAY2x1c3RlcjAudnpwdmY4bC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
