apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGF1bG9mZXJyZWlyYXNlbmhh # Base64 de 'password'
  POSTGRES_URL: amRiYzpwb3N0Z3Jlc3FsOi8vZGItc2VydmljZTo1NDMyL2xhbmNob25ldGU=
  POSTGRES_USER: cGF1bG9mZXJyZWlyYQ==
